# check what is installed in ubuntu-latest https://github.com/actions/virtual-environments
name: NOVA CI
on:
  push:
    branches: [ nova ]
  pull_request:
    branches: [ nova ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_HOME:   ${ANDROID_HOME}
      ANDROID_SDK:        ${ANDROID_HOME}
      ANDROID_NDK_HOME:   ${ANDROID_NDK_LATEST_HOME}
      ANDROID_NDK:        ${ANDROID_NDK_LATEST_HOME}
    steps:
    - uses: actions/checkout@v3
    - name: setup java17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: install packages
      run: |
        sudo apt-get update || sudo apt-get update
        sudo apt-get install -y ninja-build maven build-essential wget curl unzip git pkg-config
    - name: install recent nasm for dav1d
      run: |
        wget http://ftp.debian.org/debian/pool/main/n/nasm/nasm_2.15.05-1_amd64.deb
        sudo dpkg -i ./nasm_2.15.05-1_amd64.deb
        nasm --version
    - name: install compatible meson with dav1d
      run: |
        sudo apt-get install -y python3 python3-pip python3-setuptools python3-wheel
        sudo pip3 install meson==0.53.2
        meson --version
    - name: install repo
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/local/bin/repo > /dev/null
        sudo chmod a+x /usr/local/bin/repo
    - name: retrieve full nova source
      run: |
         mkdir nova
         cd nova
         repo init -u https://github.com/nova-video-player/aos-AVP -b nova -m v6_2.xml
         repo sync -j 4
         repo forall -c 'git checkout -t $REPO_REMOTE/$REPO_RREV'
    - name: build
      run: |
        cd nova/Video
        ./gradlew aNR
